## Introduction to R

In [1]:
#Assigning a character string to a variablema
x <- "Hello World!"

In [2]:
#Print the variable
print(x) #explicit printing

[1] "Hello World!"


In [3]:
#Assignment Operators
y = "Hello World!"
"Hello World!" -> z

In [4]:
#Implicit Printing
y

[1] "Hello World!"

In [5]:
#Variables
logical <- TRUE #boolean variable
integer <- 123L #L stands for long, for long integer (32-bit) integer
numeric <- 1.23 #numeric value contains decimal precision numeric value
character <- "ABC 123" #character string
date <- as.Date("2018-07-18") #date and time data type

In [6]:
#Displaying Variables
logical
integer
numeric
character
date

[1] TRUE

[1] 123

[1] 1.23

[1] "ABC 123"

[1] "2018-07-18"

In [7]:
# Creating a function
f <- function(x) { x+1 }

In [8]:
# Invoking a function
f(2)

[1] 3

### Vector

Vector is a basic data structure in R. It contains element of the same type. 
The data types can be logical, integer, double, character, complex or raw. 
A vector's type can be checked with the typeof() function.

In [9]:
# Creating a vector
v <- c(1, 2, 3);
v

[1] 1 2 3

In [10]:
# Creating a sequence
s <- 1:5 #ascending order
s

[1] 1 2 3 4 5

In [11]:
s <- 5:1 #descending order
s

[1] 5 4 3 2 1

In [12]:
# Creating a matrix
m <- matrix(data = 1:6, nrow=2, ncol=3) #matrix of 2*3
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [13]:
# Creating an array
a <- array(data=1:8, dim=c(2,2,2)) #array of 2*2*2
a

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

In [14]:
# Creating a list
l <- list(123.45, TRUE, 123L, "abc") #list can store heterogeneous values
l

[[1]]
[1] 123.45

[[2]]
[1] TRUE

[[3]]
[1] 123

[[4]]
[1] "abc"

In [15]:
# Creating a factor
categories <- c("Male", "Female", "Male", "Male", "Female") #list of categorical values
factor <- factor(categories) 
factor # 5 values with two levels- Male & Female
levels(factor) #list of unique name values or levels
unclass(factor)

[1] Male   Female Male   Male   Female
Levels: Female Male

[1] "Female" "Male"

[1] 2 1 2 2 1
attr(,"levels")
[1] "Female" "Male"

In [16]:
# Creating a dataframe
df <- data.frame(
Name = c("Cat", "Dog", "Cow", "Bear"),
HowMany = c(5, 10, 15, 20),
IsPet = c(TRUE, TRUE, TRUE, FALSE))
df

Name HowMany IsPet
1 Cat   5       TRUE
2 Dog  10       TRUE
3 Cow  15       TRUE
4 Bear 20      FALSE

In [17]:
# Indexing dataframes by row and column
df[1,2]

[1] 5

In [18]:
# Indexing dataframe by row
df[1,]

Name HowMany IsPet
1 Cat  5       TRUE

In [19]:
# Indexing dataframe by column
df[,2]

[1]  5 10 15 20

In [20]:
df[['HowMany']]

[1]  5 10 15 20

In [21]:
df$HowMany  #this method is generally preferred

[1]  5 10 15 20

In [22]:
# Subsetting dataframes
df[c(2,4),]

Name HowMany IsPet
2 Dog  10       TRUE
4 Bear 20      FALSE

In [23]:
df[2:4,]

Name HowMany IsPet
2 Dog  10       TRUE
3 Cow  15       TRUE
4 Bear 20      FALSE

In [24]:
df[c(TRUE, FALSE, FALSE, TRUE),]

Name HowMany IsPet
1 Cat   5       TRUE
4 Bear 20      FALSE

In [25]:
df[df$IsPet == TRUE,]

Name HowMany IsPet
1 Cat   5      TRUE 
2 Dog  10      TRUE 
3 Cow  15      TRUE

In [26]:
df[df$HowMany > 10,]

Name HowMany IsPet
3 Cow  15       TRUE
4 Bear 20      FALSE

In [27]:
df[df$Name %in% c("Cow", "Cat"),]

Name HowMany IsPet
1 Cat   5      TRUE 
3 Cow  15      TRUE

In [28]:
#Indexing in R is also applied to vectors, matrices, list, arrays in addition to dataframe

In [29]:
# R is a vectorized language
1 + 2
c(1,2,3) + c(2,4,6)

[1] 3

[1] 3 6 9

In [30]:
# Named vs Ordered Arguments
m <- matrix(data = 1:6, nrow=2, ncol=3) #matrix of 2*3
n <- matrix(1:6, 2, 3) #matrix of 2*3
m == n #it will return a matrix of true and false
identical(m,n) #two check if two matrices are identical

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE

[1] TRUE

In [31]:
# Installing Packages
install.packages("dplyr")

In [32]:
# Loading packages
library("dplyr")


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



In [33]:
# Viewing Help
?data.frame